routes/admin.php
<?php


//Admin Route

Route::get('site-maintenance/check', 'Admin\AdminController@siteMaintenanceCheck')->name('maintenance.check');
Route::get('/maintenance', 'Admin\AdminController@maintenance')->name('maintenance');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('dashboard', 'Admin\AdminController@dashboard')->name('home');

    Route::group(['middleware' => 'admin'], function () {
        Route::get('straight-league-approval', 'UserController\StraightBet@straightLeagueApproval');
        Route::post('wager-disable', 'UserController\StraightBet@WagerDisableStore')->name('wager-disable.store');
        Route::get('wager-disable-delete/{sport_league}', 'UserController\StraightBet@WagerDisableDelete');

        //Agent
        Route::resource('invoice', 'Admin\InvoiceController');
        Route::resource('agent', 'Admin\AgentController');

        // revert the changes
        //Assign User
        Route::get('assign-users', 'Admin\AgentassignController@assignUsers');
        Route::get('assign-user/create/{id}', 'Admin\AgentassignController@assignUsersCreate');
        Route::get('assign-user/delete/{id}', 'Admin\AgentassignController@assignUsersRemove');
        Route::post('assign-user/store', 'admin\agentassigncontroller@assignusersstore')->name('assign-user.store');

        //Admin
        Route::get('site-maintenance', 'Admin\AdminController@siteMaintenance');
        Route::post('site-maintenance/store', 'Admin\AdminController@siteMaintenanceStore')->name('maintenance.store');

        Route::resource('admin-manage', 'Admin\AdminController');
    });

    Route::group(['middleware' => 'admin' || 'agent' || 'subagent'], function () {
        //User
        Route::post('reset-password/{id}', 'Admin\UserController@resetPassword');
        Route::resource('user', 'Admin\UserController');
        Route::get('active-user', 'Admin\AdminController@activeUsersList')->name('user.active-user');
        Route::get('today-represent-lists', 'Admin\AdminController@todayReprestsList');
        Route::get('weekly-represent-lists', 'Admin\AdminController@weeklyReprestsList');
        Route::get('deleted-wager-lists', 'Admin\AdminController@deletedWagerListsby');
        Route::get('weekly-agents-wagers', 'Admin\AdminController@weeklyWager');
        Route::get('total-agents-wagers', 'Admin\AdminController@totalWager');

        //agentassign
        Route::get('agentassign/transaction/{id}', 'Admin\AgentassignController@transaction');
        Route::post('agentassign/transaction/store', 'Admin\AgentassignController@transactionStore')->name('transaction.store');

        Route::get('agentassign/limits/{id}', 'Admin\AgentassignController@limits');
        Route::post('agentassign/limits/store', 'Admin\AgentassignController@limitStore')->name('limit.store');

        Route::get('agentassign/pending/{id}', 'Admin\AgentassignController@pending');
        Route::get('agentassign/pending/delete/{id}', 'Admin\AgentassignController@pendingDelete');
        Route::get('agentassign/wager/{id}', 'Admin\AgentassignController@wager');

        Route::get('agentassign/notification/{id}', 'Admin\AgentassignController@notification');
        Route::post('agentassign/notification/store', 'Admin\AgentassignController@notificationStore')->name('notification.store');

        Route::get('agentassign/internet-log/{id}', 'Admin\AgentassignController@internetLog');
        Route::get('agentassign/distribution/{id}', 'Admin\AgentassignController@distribution');

        Route::get('agentassign/delete-account/{id}', 'Admin\AgentassignController@deleteAccount');
        Route::get('delete-account/{id}', 'Admin\AgentassignController@deleteAccountAction');

        //Record
        Route::get('record/weekly-figures', 'Admin\RecordController@weeklyFigures');
        Route::get('record/wagers', 'Admin\RecordController@wagers');
        Route::get('record/pending-wagers', 'Admin\RecordController@pendingWager');
        Route::get('record/delete-wagers', 'Admin\RecordController@deleteWager');
    });


    Route::group(['middleware' => 'agent'], function () {
        // Distribution
        Route::get('distribution/log', 'Admin\DistributionController@distributionLog');
        Route::get('distribution/summary', 'Admin\InvoiceController@index');

        //Sub Agent
        Route::get('subagent/assign-users', 'Admin\SubAgentController@assignUsers');
        Route::resource('subagent', 'Admin\SubAgentController');
    });

    Route::group(['middleware' => 'subagent'], function () { });
});

routes/web.php
<?php

use App\Ebet\BetResults;
use App\Ebet\Sports\Live\Tennis;
use Elasticsearch\ClientBuilder;
use App\Ebet\Sports\Live\Baseball;
use App\Ebet\Sports\Live\Football;
use App\Ebet\Results\ResultPublish;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Ebet\Sports\Live\LiveBetFormat;
use App\Ebet\Sports\Straight\StraightSport;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



include('admin.php');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', function () {
    \Illuminate\Support\Facades\Auth::logout();
    return redirect('/login');
});

Auth::routes();



   Route::get('/', 'WebsiteController@login');



   Route::get('/checkApi',function(){
         $obj =new  StraightSport(
             new \App\Ebet\Sports\Straight\Basketball('https://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/getodds/soccer?cat=basket_10',18)
            );
        return $obj->getLeagues();
   });

   Route::get('/checkresult',function(){

    return  (new ResultPublish(new App\Ebet\Results\Sports\Esport('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/esports/d-1',151)))->getObj();



   });

   Route::get('/checkliveApi',function(){
    $hockey =  new LiveBetFormat(new Baseball('http://inplay.goalserve.com/inplay-baseball.json'));
    return $hockey->getData();
   });


        Route::get('storeData','WebsiteController@storeStraightSport');
        Route::get('storeLiveData','WebsiteController@storeLiveSport');
        Route::get('storeHorseData','WebsiteController@storeHorse');
        Route::get('result','WebsiteController@getResult');
        Route::get('test_live_data','UserController\LiveBetsController@getSportsData');

        Route::get('/live-football', 'UserController\LiveBetsController@liveFootBall');

Route::group(['middleware' => ['httpReferer']], function () {
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/header-pending-data', 'WebsiteController@pendingAjax');

       // Route::get('/straight-bet', 'UserController\StraightBet@storeSports');
        Route::get('/straight-bet', 'UserController\StraightBet@index');

        Route::post('/straight_odds', 'UserController\StraightBet@straightOdds');

        /*
          required when user refresh the page
        */
        Route::get('/straight_odds', 'UserController\StraightBet@straightOdds');

        Route::get('/rules', function () {
            return view('frontend.rules');
        });

        Route::get('/account', 'WebsiteController@account');
        Route::get('/account/wager', 'WebsiteController@accountWager');
        Route::get('/pending', 'WebsiteController@pending');
        Route::get('/live-casino', 'WebsiteController@casinoLive');
        Route::get('/horses', 'UserController\HorseBet@index');
        Route::get('/guide', 'WebsiteController@guide');
        Route::get('/casino-games', 'WebsiteController@casino');
        Route::get('/casino-games/{gameName}', 'WebsiteController@casinoGames');
        //game
        Route::get('/game/{gameName}/start', 'WebsiteController@gamePlay');
        Route::post('/casino/store', 'WebsiteController@casinoHistoryStore')->name('casino.store');

        Route::post('/props-bet', 'UserController\StraightBet@propsBet');

        Route::post('/check-straight-bet', 'BetSave@index');
        Route::post ('/save-horse-bet','BetSave@saveHorseBet');
        Route::post('/check-password-straight-bet', 'BetSave@checkBetPassword');
        Route::post('/save-straight-bet', 'BetSave@saveStraightBet');
        Route::post('/save-parlay-bet','BetSave@saveParlayBet');


        /*
        |----------------------------------------------------
        | Live bets start
        |----------------------------------------------------
        */

        Route::get('/live-games', function () {
            return view('frontend.live_games');
        });

        /*
        |-----------------------------------------------------------------
        | we may use these routes to check every live bet page individually
        |---------------------------------------------------------------
        */
         Route::get('/live-basket-view', function () {
            return view('frontend.live-basket-test');
        });
        /* Route::get('/live-basket-ball-view', function () {
            return view('frontend.live_bets.live-baseball');
        }); */
        /* Route::get('/live-base-ball-view', function () {
            return view('frontend.live_bets.live-baseball');
        }); */
        Route::get('/live-sports', 'UserController\LiveBetsController@liveSports');
        Route::get('/live-sports-menu', 'UserController\LiveBetsController@liveSportsMenus');
        Route::get('/live-tennis', 'UserController\LiveBetsController@liveTennis');
        Route::get('/live-hockey', 'UserController\LiveBetsController@liveHockey');
        Route::get('/live-base-ball', 'UserController\LiveBetsController@liveBaseBall');
        Route::get('/live-basket-ball', 'UserController\LiveBetsController@liveBasketBall');
        Route::get('/live-vollyball', 'UserController\LiveBetsController@liveVolleyBall');
        Route::get('/live-motor-sport', 'UserController\LiveBetsController@liveMotorSport');
        Route::get('/live-cycling-sport', 'UserController\LiveBetsController@liveCycling');
        Route::get('/live-soccer-league', 'UserController\LiveBetsController@liveSoccerLeaguesLists');
        Route::post('/check-user-password', 'UserController\LiveBetsController@checkUserpassword');
        Route::get('/live-soccer', 'UserController\LiveBetsController@liveSoccer');
        Route::get('/live-soccer-view', 'UserController\LiveBetsController@liveSoccer');
        Route::post('/save-live-data', 'BetSave@saveLiveBet');
        Route::get('/test-result', 'WebsiteController@getResult');

        /* live hockey view on test purpose */
        Route::get('/live-hockey-view', 'UserController\LiveBetsController@liveHockeyView');
    });
});


Route::group(['prefix' => 'result'], function () {
    Route::get('/football', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Football('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/football/home',12)))->getObj();
            else $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Football('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/football/d-'.$i,12)))->getObj();
        }
        return $sportIdArr;
    });
    Route::get('/baseball', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Baseball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/baseball/home',16)))->getObj();
            else $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Baseball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/baseball/d-'.$i,16)))->getObj();
        }
        return $sportIdArr;
    });
    Route::get('/basketball', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Basketball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/bsktbl/home',18)))->getObj();
            else $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Basketball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/bsktbl/d-'.$i,18)))->getObj();
        }
        return $sportIdArr;
    });
    Route::get('/volleyball', function(){
        $obj2 = [];
        for($i=0;$i<8; $i++)
           {
               if($i==0) $obj2 += (new ResultPublish(new App\Ebet\Results\Sports\Volleyball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/volleyball/home',14)))->getObj();
               else $obj2 += (new ResultPublish(new App\Ebet\Results\Sports\Volleyball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/volleyball/d-'.$i,14)))->getObj();
           }
           return $obj2;
    });
    Route::get('/e-sport', function(){
        $obj2 = [];
        for($i=0;$i<8; $i++)
           {
               if($i==0) $obj2 += (new ResultPublish(new App\Ebet\Results\Sports\Esport('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/esports/home',151)))->getObj();
               else $obj2 += (new ResultPublish(new App\Ebet\Results\Sports\Esport('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/esports/d-'.$i,151)))->getObj();
           }
           return $obj2;
    });
    Route::get('/hockey', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Hockey('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/hockey/home',17)))->getObj();
            else $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Hockey('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/hockey/d-'.$i,17)))->getObj();
        }
        return $sportIdArr;
    });
    Route::get('/soccer', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Soccer('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/soccernew/home',1)))->getObj();

resources/views/admin/include/footer.blade.php
<footer class="main-footer text-center">
    <strong> &copy; </strong>
    {{ date('Y') }} All rights reserved.
</footer>

resources/views/admin/include/header.blade.php
<style>
    @media only screen and (max-width: 364px) {
        .logout-title {
            font-size: 12px;
        }
    }
</style>
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li><h5>
                <a class="text-danger logout-title" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="fas fa-sign-out-alt"></i> Sign out</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </h5>
        </li>
    </ul>
</nav>

resources/views/admin/include/navbar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <a href="{{ url('admin/dashboard') }}" class="brand-link">
        <img src="{{ asset('admin/dist') }}/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        @if(Auth::user()->role == 'admin')
            <span class="brand-text font-weight-light">Admin </span><small style="font-size: 15px">Control Panel</small>
        @elseif(Auth::user()->role == 'agent')
            <span class="brand-text font-weight-light">Agent </span><small style="font-size: 15px">Control Panel</small>
        @elseif(Auth::user()->role == 'subagent')
            <span class="brand-text font-weight-light">Sub Agent </span><small style="font-size: 15px">Control Panel</small>
        @endif
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('admin/dist') }}/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ Auth::user()->name }}</a>
            </div>

        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item">
                    <a href="{{ url('admin/dashboard') }}" class="nav-link {{ Request::is('admin/dashboard') ? 'active':'' }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>


                @if(Auth::user()->role == 'admin')
                <li class="nav-item">
                    <a href="{{ url('admin/straight-league-approval') }}" class="nav-link {{ Request::is('admin/straight-league-approval') ? 'active':'' }}">
                        <i class="nav-icon fas fa-list"></i>
                        <p>Straight League Approval</p>
                    </a>
                </li>
                @endif

                <li class="nav-item has-treeview {{ Request::is('admin/admin-manage*') || Request::is('admin/assign-user*') || Request::is('admin/user*') || Request::is('admin/agent*') || Request::is('admin/active-user') ? 'menu-open':'' }}">
                    <a href="#" class="nav-link {{ Request::is('admin/admin-manage*') || Request::is('admin/assign-user*') || Request::is('admin/user*') || Request::is('admin/agent*') || Request::is('admin/active-user') ? 'active':'' }}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            User Management
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('user.index') }}" class="nav-link {{ Request::is('admin/user') || Request::is('admin/assign-user*') || Request::is('admin/user/*/edit') ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Users</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('user.active-user') }}" class="nav-link {{ Request::is('admin/active-user')? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Active Users</p>
                            </a>
                        </li>

                        @if(Auth::user()->role == 'admin')
                        <li class="nav-item">
                            <a href="{{ route('agent.index') }}" class="nav-link {{ Request::is('admin/agent') || Request::is('admin/agent/*/edit') ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Agents</p>
                            </a>
                        </li>

                       {{--  <li class="nav-item">
                            <a href="{{ url('admin/agents-users/lists') }}" class="nav-link {{ Request::is('admin/agents-users/lists') ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Assign user</p>
                            </a>
                        </li> --}}

                        <li class="nav-item">
                            <a href="{{ route('admin-manage.index') }}" class="nav-link {{ Request::is('admin/admin-manage*') ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Administrator</p>
                            </a>
                        </li>
                        @endif
                    </ul>
                </li>


                @if(Auth::user()->role != 'subagent')
                    <li class="nav-item has-treeview {{ Request::is('admin/record*') ? 'menu-open':'' }}">
                        <a href="#" class="nav-link {{ Request::is('admin/record*') ? 'active':'' }}">
                            <i class="nav-icon fas fa-list-alt"></i>
                            <p>
                                User Record
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">

                            @if(Auth::user()->role == 'agent')
                            <li class="nav-item">
                                <a href="{{ url('admin/record/weekly-figures') }}" class="nav-link {{ Request::is('admin/record/weekly-figures') ? 'active':'' }}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Weekly Figures</p>
                                </a>
                            </li>
                            @endif

                            <li class="nav-item">
                                <a href="{{ url('admin/record/wagers') }}" class="nav-link {{ Request::is('admin/record/wagers') ? 'active':'' }}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>All Wagers</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ url('admin/record/pending-wagers') }}" class="nav-link {{ Request::is('admin/record/pending-wagers') ? 'active':'' }}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Pending Wagers</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ url('admin/record/delete-wagers') }}" class="nav-link {{ Request::is('admin/record/delete-wagers') ? 'active':'' }}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Deleted Wagers</p>
                                </a>
                            </li>

                        </ul>
                    </li>
                @endif


                @if(Auth::user()->role == 'agent')
                <li class="nav-item has-treeview {{ Request::is('admin/distribution*') ? 'menu-open':'' }}">
                    <a href="#" class="nav-link {{ Request::is('admin/distribution*') ? 'active':'' }}">
                        <i class="nav-icon fas fa-chart-bar"></i>
                        <p>
                            Distribution
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ url('admin/distribution/summary') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Agent Summary</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{{ url('admin/distribution/log') }}" class="nav-link {{ Request::is('admin/distribution/log') ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Total Weekly Distribution</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview {{ Request::is('admin/subagent*') ? 'menu-open':'' }}">
                    <a href="#" class="nav-link {{ Request::is('admin/subagent*') ? 'active':'' }}">
                        <i class="nav-icon fas fa-chart-area"></i>
                        <p>
                            Manage Sub-Agent
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('subagent.index') }}" class="nav-link {{ Request::is('admin/subagent') || Request::is('admin/subagent/*/edit') ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Manage Sub-Agent</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{{ url('admin/subagent/assign-users') }}" class="nav-link {{ Request::is('admin/subagent/assign-users') ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Assign User To Sub-Agent</p>
                            </a>
                        </li>
                    </ul>
                </li>
                @endif

                @if(Auth::user()->role == 'admin')
                <li class="nav-item">
                    <a href="{{ url('admin/invoice') }}" class="nav-link {{ Request::is('admin/invoice') ? 'active':'' }}">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>Invoices</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url('admin/site-maintenance') }}" class="nav-link {{ Request::is('admin/site-maintenance') ? 'active':'' }}">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>Site Maintenance</p>
                    </a>
                </li>
                @endif


            </ul>
        </nav>
    </div>
</aside>