routes/admin.php
<?php


//Admin Route

Route::get('site-maintenance/check', 'Admin\AdminController@siteMaintenanceCheck')->name('maintenance.check');
Route::get('/maintenance', 'Admin\AdminController@maintenance')->name('maintenance');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('dashboard', 'Admin\AdminController@dashboard')->name('home');

    Route::group(['middleware' => 'admin'], function () {
        Route::get('straight-league-approval', 'UserController\StraightBet@straightLeagueApproval');
        Route::post('wager-disable', 'UserController\StraightBet@WagerDisableStore')->name('wager-disable.store');
        Route::get('wager-disable-delete/{sport_league}', 'UserController\StraightBet@WagerDisableDelete');

        //Agent
        Route::resource('invoice', 'Admin\InvoiceController');
        Route::resource('agent', 'Admin\AgentController');

        // revert the changes
        //Assign User
        Route::get('assign-users', 'Admin\AgentassignController@assignUsers');
        Route::get('assign-user/create/{id}', 'Admin\AgentassignController@assignUsersCreate');
        Route::get('assign-user/delete/{id}', 'Admin\AgentassignController@assignUsersRemove');
        Route::post('assign-user/store', 'admin\agentassigncontroller@assignusersstore')->name('assign-user.store');

        //Admin
        Route::get('site-maintenance', 'Admin\AdminController@siteMaintenance');
        Route::post('site-maintenance/store', 'Admin\AdminController@siteMaintenanceStore')->name('maintenance.store');

        Route::resource('admin-manage', 'Admin\AdminController');
    });

    Route::group(['middleware' => 'admin' || 'agent' || 'subagent'], function () {
        //User
        Route::post('reset-password/{id}', 'Admin\UserController@resetPassword');
        Route::resource('user', 'Admin\UserController');
        Route::get('active-user', 'Admin\AdminController@activeUsersList')->name('user.active-user');
        Route::get('today-represent-lists', 'Admin\AdminController@todayReprestsList');
        Route::get('weekly-represent-lists', 'Admin\AdminController@weeklyReprestsList');
        Route::get('deleted-wager-lists', 'Admin\AdminController@deletedWagerListsby');
        Route::get('weekly-agents-wagers', 'Admin\AdminController@weeklyWager');
        Route::get('total-agents-wagers', 'Admin\AdminController@totalWager');

        //agentassign
        Route::get('agentassign/transaction/{id}', 'Admin\AgentassignController@transaction');
        Route::post('agentassign/transaction/store', 'Admin\AgentassignController@transactionStore')->name('transaction.store');

        Route::get('agentassign/limits/{id}', 'Admin\AgentassignController@limits');
        Route::post('agentassign/limits/store', 'Admin\AgentassignController@limitStore')->name('limit.store');

        Route::get('agentassign/pending/{id}', 'Admin\AgentassignController@pending');
        Route::get('agentassign/pending/delete/{id}', 'Admin\AgentassignController@pendingDelete');
        Route::get('agentassign/wager/{id}', 'Admin\AgentassignController@wager');

        Route::get('agentassign/notification/{id}', 'Admin\AgentassignController@notification');
        Route::post('agentassign/notification/store', 'Admin\AgentassignController@notificationStore')->name('notification.store');

        Route::get('agentassign/internet-log/{id}', 'Admin\AgentassignController@internetLog');
        Route::get('agentassign/distribution/{id}', 'Admin\AgentassignController@distribution');

        Route::get('agentassign/delete-account/{id}', 'Admin\AgentassignController@deleteAccount');
        Route::get('delete-account/{id}', 'Admin\AgentassignController@deleteAccountAction');

        //Record
        Route::get('record/weekly-figures', 'Admin\RecordController@weeklyFigures');
        Route::get('record/wagers', 'Admin\RecordController@wagers');
        Route::get('record/pending-wagers', 'Admin\RecordController@pendingWager');
        Route::get('record/delete-wagers', 'Admin\RecordController@deleteWager');
    });


    Route::group(['middleware' => 'agent'], function () {
        // Distribution
        Route::get('distribution/log', 'Admin\DistributionController@distributionLog');
        Route::get('distribution/summary', 'Admin\InvoiceController@index');

        //Sub Agent
        Route::get('subagent/assign-users', 'Admin\SubAgentController@assignUsers');
        Route::resource('subagent', 'Admin\SubAgentController');
    });

    Route::group(['middleware' => 'subagent'], function () { });
});

routes/web.php
<?php

use App\Ebet\BetResults;
use App\Ebet\Sports\Live\Tennis;
use Elasticsearch\ClientBuilder;
use App\Ebet\Sports\Live\Baseball;
use App\Ebet\Sports\Live\Football;
use App\Ebet\Results\ResultPublish;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Ebet\Sports\Live\LiveBetFormat;
use App\Ebet\Sports\Straight\StraightSport;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



include('admin.php');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', function () {
    \Illuminate\Support\Facades\Auth::logout();
    return redirect('/login');
});

Auth::routes();



   Route::get('/', 'WebsiteController@login');



   Route::get('/checkApi',function(){
         $obj =new  StraightSport(
             new \App\Ebet\Sports\Straight\Basketball('https://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/getodds/soccer?cat=basket_10',18)
            );
        return $obj->getLeagues();
   });

   Route::get('/checkresult',function(){

    return  (new ResultPublish(new App\Ebet\Results\Sports\Esport('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/esports/d-1',151)))->getObj();



   });

   Route::get('/checkliveApi',function(){
    $hockey =  new LiveBetFormat(new Baseball('http://inplay.goalserve.com/inplay-baseball.json'));
    return $hockey->getData();
   });


        Route::get('storeData','WebsiteController@storeStraightSport');
        Route::get('storeLiveData','WebsiteController@storeLiveSport');
        Route::get('storeHorseData','WebsiteController@storeHorse');
        Route::get('result','WebsiteController@getResult');
        Route::get('test_live_data','UserController\LiveBetsController@getSportsData');

        Route::get('/live-football', 'UserController\LiveBetsController@liveFootBall');

Route::group(['middleware' => ['httpReferer']], function () {
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/header-pending-data', 'WebsiteController@pendingAjax');

       // Route::get('/straight-bet', 'UserController\StraightBet@storeSports');
        Route::get('/straight-bet', 'UserController\StraightBet@index');

        Route::post('/straight_odds', 'UserController\StraightBet@straightOdds');

        /*
          required when user refresh the page
        */
        Route::get('/straight_odds', 'UserController\StraightBet@straightOdds');

        Route::get('/rules', function () {
            return view('frontend.rules');
        });

        Route::get('/account', 'WebsiteController@account');
        Route::get('/account/wager', 'WebsiteController@accountWager');
        Route::get('/pending', 'WebsiteController@pending');
        Route::get('/live-casino', 'WebsiteController@casinoLive');
        Route::get('/horses', 'UserController\HorseBet@index');
        Route::get('/guide', 'WebsiteController@guide');
        Route::get('/casino-games', 'WebsiteController@casino');
        Route::get('/casino-games/{gameName}', 'WebsiteController@casinoGames');
        //game
        Route::get('/game/{gameName}/start', 'WebsiteController@gamePlay');
        Route::post('/casino/store', 'WebsiteController@casinoHistoryStore')->name('casino.store');

        Route::post('/props-bet', 'UserController\StraightBet@propsBet');

        Route::post('/check-straight-bet', 'BetSave@index');
        Route::post ('/save-horse-bet','BetSave@saveHorseBet');
        Route::post('/check-password-straight-bet', 'BetSave@checkBetPassword');
        Route::post('/save-straight-bet', 'BetSave@saveStraightBet');
        Route::post('/save-parlay-bet','BetSave@saveParlayBet');


        /*
        |----------------------------------------------------
        | Live bets start
        |----------------------------------------------------
        */

        Route::get('/live-games', function () {
            return view('frontend.live_games');
        });

        /*
        |-----------------------------------------------------------------
        | we may use these routes to check every live bet page individually
        |---------------------------------------------------------------
        */
         Route::get('/live-basket-view', function () {
            return view('frontend.live-basket-test');
        });
        /* Route::get('/live-basket-ball-view', function () {
            return view('frontend.live_bets.live-baseball');
        }); */
        /* Route::get('/live-base-ball-view', function () {
            return view('frontend.live_bets.live-baseball');
        }); */
        Route::get('/live-sports', 'UserController\LiveBetsController@liveSports');
        Route::get('/live-sports-menu', 'UserController\LiveBetsController@liveSportsMenus');
        Route::get('/live-tennis', 'UserController\LiveBetsController@liveTennis');
        Route::get('/live-hockey', 'UserController\LiveBetsController@liveHockey');
        Route::get('/live-base-ball', 'UserController\LiveBetsController@liveBaseBall');
        Route::get('/live-basket-ball', 'UserController\LiveBetsController@liveBasketBall');
        Route::get('/live-vollyball', 'UserController\LiveBetsController@liveVolleyBall');
        Route::get('/live-motor-sport', 'UserController\LiveBetsController@liveMotorSport');
        Route::get('/live-cycling-sport', 'UserController\LiveBetsController@liveCycling');
        Route::get('/live-soccer-league', 'UserController\LiveBetsController@liveSoccerLeaguesLists');
        Route::post('/check-user-password', 'UserController\LiveBetsController@checkUserpassword');
        Route::get('/live-soccer', 'UserController\LiveBetsController@liveSoccer');
        Route::get('/live-soccer-view', 'UserController\LiveBetsController@liveSoccer');
        Route::post('/save-live-data', 'BetSave@saveLiveBet');
        Route::get('/test-result', 'WebsiteController@getResult');

        /* live hockey view on test purpose */
        Route::get('/live-hockey-view', 'UserController\LiveBetsController@liveHockeyView');
    });
});


Route::group(['prefix' => 'result'], function () {
    Route::get('/football', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Football('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/football/home',12)))->getObj();
            else $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Football('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/football/d-'.$i,12)))->getObj();
        }
        return $sportIdArr;
    });
    Route::get('/baseball', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Baseball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/baseball/home',16)))->getObj();
            else $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Baseball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/baseball/d-'.$i,16)))->getObj();
        }
        return $sportIdArr;
    });
    Route::get('/basketball', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Basketball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/bsktbl/home',18)))->getObj();
            else $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Basketball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/bsktbl/d-'.$i,18)))->getObj();
        }
        return $sportIdArr;
    });
    Route::get('/volleyball', function(){
        $obj2 = [];
        for($i=0;$i<8; $i++)
           {
               if($i==0) $obj2 += (new ResultPublish(new App\Ebet\Results\Sports\Volleyball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/volleyball/home',14)))->getObj();
               else $obj2 += (new ResultPublish(new App\Ebet\Results\Sports\Volleyball('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/volleyball/d-'.$i,14)))->getObj();
           }
           return $obj2;
    });
    Route::get('/e-sport', function(){
        $obj2 = [];
        for($i=0;$i<8; $i++)
           {
               if($i==0) $obj2 += (new ResultPublish(new App\Ebet\Results\Sports\Esport('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/esports/home',151)))->getObj();
               else $obj2 += (new ResultPublish(new App\Ebet\Results\Sports\Esport('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/esports/d-'.$i,151)))->getObj();
           }
           return $obj2;
    });
    Route::get('/hockey', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Hockey('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/hockey/home',17)))->getObj();
            else $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Hockey('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/hockey/d-'.$i,17)))->getObj();
        }
        return $sportIdArr;
    });
    Route::get('/soccer', function(){
        $sportIdArr = [];
        for($i=0;$i<8; $i++)
        {
            if($i==0)  $sportIdArr += (new ResultPublish(new App\Ebet\Results\Sports\Soccer('http://www.goalserve.com/getfeed/4d5f7e372939425c2b7d08d76ad955ff/soccernew/home',1)))->getObj();

resources/views/admin/subagent/assign_users.blade.php
@extends('layouts.admin_layout')


@section('title')
    Admin / Assign User
@endsection

@section('body-title')
    Assign User
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item active">Assign User</li>
@endsection

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Assign User</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table data-page-length='50' class="table myTbl table-bordered table-striped">
                            <thead>
                            <tr>
                                <th width="15%">S.No</th>
                                <th>Agent</th>
                                <th width="10%">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $key => $user)
                            <tr>
                                <td>{{ ++$key }}</td>
                                <td>{{ $user->username }}</td>
                                <td><a href="{{ url('admin/assign-user/create/'. $user->id) }}" class="btn btn-sm btn-info"><i class="fas fa-edit"></i></a></td>
                            </tr>
                            @endforeach

                            </tbody>

                        </table>
                    </div>
                </div>

            </div>

        </div><!-- /.container-fluid -->
    </section>
@endsection
@section('page_js')

@endsection

resources/views/admin/subagent/edit.blade.php
@extends('layouts.admin_layout')


@section('title')
    Admin / {{ $data->name }} / Edit
@endsection

@section('body-title')
    Sub Agent Edit
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('subagent.index') }}">User</a></li>
    <li class="breadcrumb-item active">Edit</li>
@endsection

@section('content')
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12 col-sm-12 col-lg-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">
                               Sub Agent Edit
                            </h3>

                        </div>

                        <form  method="post" action="{!! route('subagent.update', $data->id)!!}">
                            @method('PATCH')
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="">User Name</label>
                                    <input type="text" class="form-control" id="username" name="username" value="{{ $data->username }}" placeholder="Enter username">
                                    @if ($errors->has('username'))
                                        <small class="text-danger">{{ $errors->first('username') }}</small>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label for="">User Full Name</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{ $data->name }}" placeholder="Enter User Full Name">
                                    @if ($errors->has('name'))
                                        <small class="text-danger">{{ $errors->first('name') }}</small>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label for="">User Email</label>
                                    <input type="email" class="form-control" id="email" name="email" value="{{ $data->email }}" placeholder="Enter email">
                                    @if ($errors->has('email'))
                                        <small class="text-danger">{{ $errors->first('email') }}</small>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label for="">User Referred By</label>
                                    <input type="text" class="form-control" id="referred_by" name="referred_by" value="{{ $data->referred_by }}" placeholder="Enter Referred By">
                                    @if ($errors->has('referred_by'))
                                        <small class="text-danger">{{ $errors->first('referred_by') }}</small>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <label for="">Account Status</label>
                                        </div>
                                        <div class="col-md-1">
                                            <div class="custom-control custom-radio">
                                                <input class="custom-control-input" type="radio" {{ $data->status == 1 ? 'checked':'' }} value="1" id="open" name="account_status">
                                                <label for="open" class="custom-control-label">Open</label>
                                            </div>
                                        </div>
                                        <div class="col-md-1">
                                            <div class="custom-control custom-radio">
                                                <input class="custom-control-input" type="radio" {{ $data->status == 0 ? 'checked':'' }} value="0" id="close" name="account_status">
                                                <label for="close" class="custom-control-label">Close</label>
                                            </div>
                                        </div>
                                    </div>
                                    @if ($errors->has('account_status'))
                                        <small class="text-danger">{{ $errors->first('account_status') }}</small>
                                    @endif
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                        <!-- /.card -->
                    </div>


                    <div class="card card-default">
                        <div class="card-header">
                            <h3 class="card-title">Reset Password</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" action="{{ url('admin/reset-password', $data->id) }}" method="post">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Enter Password</label>
                                    <input type="password" id="password" name="password" value="{{ old('password') }}" class="form-control" placeholder="Password" required>
                                    @if ($errors->has('password'))
                                        <small class="text-danger">{{ $errors->first('password') }}</small>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputPassword1">Re-enter Password</label>
                                    <input type="password" id="password_confirmation" value="{{ old('password_confirmation') }}" name="password_confirmation" class="form-control" placeholder="Retype password" required>
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- /.modal -->
@endsection

@section('page_js')

@endsection

resources/views/admin/subagent/index.blade.php
@extends('layouts.admin_layout')

@section('title')
    Admin / Sub Agent
@endsection

@section('body-title')
    Sub Agent
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item active">Sub Agent</li>
@endsection

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-2">
                            <button type="button" data-toggle="modal" data-target="#modal-lg" class="btn btn-block btn-outline-secondary btn-sm">Create New Sub-Agent</button>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example1" data-page-length='50' class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>S No.</th>
                                <th>Username</th>
                                <th>Name</th>
                                <th>User</th>
                                <th>Active User</th>
                                <th>Last Login</th>
                                <th>Registered</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(!empty($data))
                                @foreach($data as $key => $user)
                                <tr>
                                    <td>{{ ++$key }}</td>
                                    <td>
                                        <a href="{{ url('admin/subagent/'.$user->id) }}/edit">{{ $user->username }}</a>
                                    </td>
                                    <td>{{ $user->name }}</td>
                                    <td></td>
                                    <td></td>
                                    <td>{{ isset($user->lastLogin->created_at) ? _getDate(strtotime($user->lastLogin->created_at)).' '. _getTime(strtotime($user->lastLogin->created_at)):'' }}</td>
                                    <td>{{ _getDate(strtotime($user->registered)).' '. _getTime(strtotime($user->registered)) }}</td>
                                </tr>
                                @endforeach
                            @endif

                            </tbody>

                        </table>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="modal fade" id="modal-lg">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header bg-teal">
                    <h4 class="modal-title">Create New User</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form  method="post" action="{{ route('subagent.store') }}">
                    @csrf
                    <div class="modal-body">
                        <div class="body">
                            <div class="form-group">
                                <input type="text" id="name" name="name" value="{{ old('name') }}" class="form-control" placeholder="Full name" required>
                                @if ($errors->has('name'))
                                    <small class="text-danger">{{ $errors->first('name') }}</small>
                                @endif
                            </div>
                            <div class="form-group">
                                <input type="email" id="email" name="email" value="{{ old('email') }}" class="form-control" placeholder="E-mail">
                                @if ($errors->has('email'))
                                    <small class="text-danger">{{ $errors->first('email') }}</small>
                                @endif
                            </div>
                            <div class="form-group">
                                <input type="text" id="referred_by" name="referred_by" value="{{ old('referred_by') }}" class="form-control" placeholder="Referred By">
                                @if ($errors->has('referred_by'))
                                    <small class="text-danger">{{ $errors->first('referred_by') }}</small>
                                @endif
                            </div>
                            <div class="form-group">
                                <input type="text" id="username" name="username" value="{{ old('username') }}" class="form-control" placeholder="Username">
                                @if ($errors->has('username'))
                                    <small class="text-danger">{{ $errors->first('username') }}</small>
                                @endif
                            </div>
                            <div class="form-group">
                                <input type="password" id="password" name="password" value="{{ old('password') }}" class="form-control" placeholder="Password" required>
                                @if ($errors->has('password'))
                                    <small class="text-danger">{{ $errors->first('password') }}</small>
                                @endif
                            </div>
                            <div class="form-group">
                                <input type="password" id="password_confirmation" value="{{ old('password_confirmation') }}" name="password_confirmation" class="form-control" placeholder="Retype password" required>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Sign Up</button>
                    </div>
                </form>

            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
@endsection

@section('page_js')

@endsection